### ISSUE TITLE
Difficulty in running the code

### ISSUE THREAD

**Issue by iRayJay** [MedARC-AI/MindEyeV2#1]
Thank you for your excellent work!

I have noticed that you have incorporated the deepspeed framework into MindEyeV2, which sets it apart from MindEyeV1 (fMRI-reconstruction-NSD). Does this mean that it is now possible to execute the code on more widely available GPUs like the 3090/4090, instead of the A100 you used?

Furthermore, I kindly request a comprehensive list of the necessary dependencies, including their specific versions (e.g., deepspeed, accelerate). I encountered some errors while running your code, and I suspect they may be due to using incorrect versions of the dependencies.

Additionally, I would greatly appreciate it if you could share the command line (arguments and configurations) required to successfully run the code (both single GPU and multi-GPU).

**Comment by PaulScotti** [comment]
This MindEyeV2 is a work-in-progress and not fully functional; we will make things more accessible after we develop the framework. Alternatively we welcome your help in revising this repo to fix the errors that you are referring to! We are developing this repo in the MedARC discord server, where these discussions should take place.
