### ISSUE TITLE
Difference between MindEyeV1 and V2

### ISSUE THREAD

**Issue by Xiangtaokong** [MedARC-AI/MindEyeV2#20]
Thank you for your outstanding work and detailed open source.

I would like to ask what is the main difference between this V2 version and the previous version (https://github.com/MedARC-AI/fMRI-reconstruction-NSD). Like adding new features? If I want to develop a related project, which version is better to use?

**Comment by PaulScotti** [comment]
You should use this one -- the arxiv paper comes out today so please check it out! Also if you are interested in adding new features / related work and are open to collaboration i highly suggest joining our MedARC Discord and sharing your ideas in the MindEye3 channel

Discord: https://discord.gg/pMhsYwJUQu
MedARC Neuroimaging & AI Lab: medarc.ai/fmri
