### ISSUE TITLE
Details about pre-trained model name

### ISSUE THREAD

**Issue by gongzix** [MedARC-AI/MindEyeV2#21]
Thank your for your great work share!
Could you explained the model's name in train_log/ ?In the paper, you mentioned that you just fine-tuned new subject's regression alignment , and you trained other subjects together. For example, I wanna to know whether 'final_subj01_pretrained_40sess_24bs' denotes multi-subject's model with subject1's regression models, or just single model trained for subject 1. And I actually concerned which is the model fine-tuned for held-out subject. Is that 'final_subj01_pretrained_1sess_24bs' ? If there is, which sessions you used for 1 Hour data? Thanks again.

**Comment by PaulScotti** [comment]
Thanks I should update the README about this... 

"final_subj01_pretrained_1sess_24bs" refers to the model that was pretrained on subjects 2-8 and then fine-tuned on the first session of data from subject 1

**Comment by gongzix** [comment]
Thanks for your timely reply, my problem has been solved.
