### ISSUE TITLE
How to get the original coco idx

### ISSUE THREAD

**Issue by Boltzmachine** [MedARC-AI/MindEyeV2#33]

**Comment by PaulScotti** [comment]
Please refer to this section of the readme

<img width="866" alt="image" src="https://github.com/user-attachments/assets/36401527-4eb1-4141-a4d7-74695d4294be">

**Comment by Boltzmachine** [comment]
Thanks so much! I Just want to double check that you understand that I want to retrieve the coco index in the original coco dataset rather than the indices in the NSD dataset.

**Comment by PaulScotti** [comment]
Ah sorry, I see -- you can consult this file and match the NSD indices to the actual COCO index

https://natural-scenes-dataset.s3-us-east-2.amazonaws.com/nsddata/experiments/nsd/nsd_stim_info_merged.csv

**Comment by Boltzmachine** [comment]
Thanks so much! Sorry my initial inquiry is ambitious
