### ISSUE TITLE
add link to Natural Scenes T&C on HF dataset card

### ISSUE THREAD

**Issue by dmarx** [MedARC-AI/MindEyeV2#9]
via https://huggingface.co/datasets/pscotti/mindeyev2

> Using these files requires that you have already agreed to the Natural Scenes Dataset's Terms and Conditions.

I don't know what this dataset is off hand and the name is generic enough that I'm not confident that I would find the same dataset referenced if I googled it. Would be helpful to provide a URL to eliminate this ambiguity.

**Comment by mihirneal** [comment]
This is the Natural Scenes Dataset but curated specifically for MindEyeV2. We'll contextualize everything once our entire codebase is public. 2 weeks.

**Comment by PaulScotti** [comment]
Yes we still need to finish MindEye2 before we work on cleaning up this repo and better explaining how others can use it. Appreciate that you are interested in this project though, please feel free to let us know any issues after we release the preprint for this project (which should be next month)
